#!/usr/bin/env bash
# Mission Control — first-time release install.
#
# Usage:
#   bash deploy/release/install.sh <tarball>
#
# Layout created:
#   ~/mission-control/
#     current -> versions/vX.Y.Z        (symlink, atomic-swappable)
#     versions/vX.Y.Z/                  (tarball contents)
#   ~/.mission-control/
#     .env.local                        (AUTH_PASSWORD, AUTH_SECRET, …)
#     data/                             (morning-report output, backups, …)
#     db.sqlite                         (created by the app on first run)
#     gateway-device-key.pem            (created by the app on first run)
#
# After install, subsequent versions drop into versions/ and the UI upgrade
# flow (or deploy/release/upgrade.sh) swaps the symlink + restarts.

set -euo pipefail

TARBALL="${1:-}"
PREFIX="${PREFIX:-$HOME/mission-control}"
STATE="${STATE:-$HOME/.mission-control}"
SERVICE="${SERVICE:-mission-control}"
INSTALL_PORT="${INSTALL_PORT:-3737}"
SYSTEMD_DIR="$HOME/.config/systemd/user"

die() { echo "✗ $*" >&2; exit 1; }
log() { echo "• $*"; }

[[ -n "$TARBALL" ]] || die "usage: bash install.sh <path/to/mission-control-vX.Y.Z-linux-x64.tar.gz>"
[[ -f "$TARBALL" ]] || die "tarball not found: $TARBALL"

# Parse version from filename — falls back to reading version.json inside the
# tarball if the filename doesn't match the expected pattern.
VERSION="$(basename "$TARBALL" | sed -En 's/^mission-control-v([0-9]+\.[0-9]+\.[0-9]+)-.*\.tar\.gz$/\1/p')"
if [[ -z "$VERSION" ]]; then
  VERSION="$(tar xzOf "$TARBALL" ./version.json 2>/dev/null | sed -En 's/.*"version": *"([^"]+)".*/\1/p' || true)"
fi
[[ -n "$VERSION" ]] || die "could not determine version from $TARBALL"

log "installing Mission Control v$VERSION"
log "  prefix: $PREFIX"
log "  state:  $STATE"

# Require node >= 20 (release is built with --target=node20).
NODE_BIN="$(command -v node || true)"
[[ -n "$NODE_BIN" ]] || die "node not found in PATH — install Node.js 20+ first"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[[ "$NODE_MAJOR" -ge 20 ]] || die "node >= 20 required (found $(node --version))"

# --- 1. Directory layout ---
mkdir -p "$PREFIX/versions" "$STATE/data" "$STATE/logs"

VERSION_DIR="$PREFIX/versions/v$VERSION"
if [[ -d "$VERSION_DIR" ]]; then
  die "$VERSION_DIR already exists — remove it first, or use upgrade.sh"
fi

log "extracting tarball → $VERSION_DIR"
mkdir -p "$VERSION_DIR"
tar xzf "$TARBALL" -C "$VERSION_DIR"

# --- 2. State bootstrap (.env.local with a fresh password) ---
ENV_FILE="$STATE/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  log "generating state/.env.local"
  GATEWAY_TOKEN=""
  if [[ -f "$HOME/.openclaw/openclaw.json" ]]; then
    GATEWAY_TOKEN="$(node -e "try{const c=JSON.parse(require('fs').readFileSync(process.env.HOME+'/.openclaw/openclaw.json','utf8'));process.stdout.write(c?.gateway?.auth?.token||'')}catch(e){}" || true)"
  fi
  PASSWORD="$(node -e "process.stdout.write(require('crypto').randomBytes(16).toString('base64url'))")"
  SECRET="$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('base64url'))")"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/release/install.sh on $(date -Iseconds)
OPENCLAW_GATEWAY_WS=ws://127.0.0.1:18789
OPENCLAW_GATEWAY_HTTP=http://127.0.0.1:18789
OPENCLAW_TOKEN=$GATEWAY_TOKEN

AUTH_PASSWORD=$PASSWORD
AUTH_SECRET=$SECRET

PORT=$INSTALL_PORT
HOST=0.0.0.0
EOF
  chmod 600 "$ENV_FILE"
else
  log "re-using existing state/.env.local"
fi

# --- 3. Link versioned dir to persistent state ---
# Symlinking .env.local lets the server's bootstrap check (existsSync) pass,
# skipping its own .env.local generator — so the state .env.local is the
# single source of truth across upgrades.
ln -sf "$ENV_FILE" "$VERSION_DIR/.env.local"
# Data dir (morning-report output, backups, etc.) must survive upgrades.
rm -rf "$VERSION_DIR/data" 2>/dev/null || true
ln -sf "$STATE/data" "$VERSION_DIR/data"

# --- 4. current → new version (atomic swap) ---
ln -sfn "$VERSION_DIR" "$PREFIX/current"
log "current → versions/v$VERSION"

# --- 5. Log file ---
# Dashboard writes stdout to $STATE/logs/mission-control.log via the systemd
# drop-in. Owner can tail without sudo. fail2ban (optional) reads the same
# path — see deploy/fail2ban/README.md for the setup that renders a jail.d
# config pointing at the absolute path.
LOG_FILE="$STATE/logs/mission-control.log"
[[ -f "$LOG_FILE" ]] || touch "$LOG_FILE"
chmod 640 "$LOG_FILE"

# --- 6. systemd user unit ---
mkdir -p "$SYSTEMD_DIR"
TMPL_DIR="$(cd "$(dirname "$0")" && pwd)"
sed -e "s|__NODE_BIN__|$NODE_BIN|g" \
    -e "s|__STATE__|$STATE|g" \
    -e "s|__PREFIX__|$PREFIX|g" \
  "$TMPL_DIR/mission-control.service.tmpl" \
  > "$SYSTEMD_DIR/$SERVICE.service"
log "wrote $SYSTEMD_DIR/$SERVICE.service"

systemctl --user daemon-reload
systemctl --user enable "$SERVICE" >/dev/null
systemctl --user restart "$SERVICE"

# Linger so the service runs without an active login session.
if ! loginctl show-user "$USER" 2>/dev/null | grep -q "Linger=yes"; then
  if command -v loginctl >/dev/null; then
    log "enabling linger (may prompt for sudo)"
    sudo loginctl enable-linger "$USER" || log "  (non-fatal) could not enable linger; service will stop on logout"
  fi
fi

# Tailscale operator: lets the service user run `tailscale serve / funnel`
# without sudo. Required for the dashboard's Obsidian → Tailscale HTTPS
# (Serve / Funnel) feature. Skipped silently if tailscale isn't installed.
if command -v tailscale >/dev/null 2>&1; then
  CURRENT_OPERATOR="$(tailscale debug prefs 2>/dev/null | sed -En 's/.*"OperatorUser": *"([^"]*)".*/\1/p' | head -1)"
  if [[ "$CURRENT_OPERATOR" != "$USER" ]]; then
    log "setting tailscale operator to $USER (may prompt for sudo)"
    if sudo -n true 2>/dev/null || sudo true 2>/dev/null; then
      if ! sudo tailscale set --operator="$USER" 2>/dev/null; then
        log "  (non-fatal) sudo tailscale set --operator failed"
        log "  → run manually on the server: sudo tailscale set --operator=$USER"
      fi
    else
      log "  (non-fatal) sudo not available for tailscale operator setup"
      log "  → run manually on the server when convenient:"
      log "      sudo tailscale set --operator=$USER"
    fi
  fi
fi

# --- 6. Health check ---
log "waiting for /api/health …"
PORT="$(grep -E '^PORT=' "$ENV_FILE" | head -1 | cut -d= -f2)"
PORT="${PORT:-3737}"
HEALTH_URL="http://127.0.0.1:$PORT/api/health"
for i in $(seq 1 30); do
  RESPONSE="$(curl -sf "$HEALTH_URL" 2>/dev/null || true)"
  if [[ -n "$RESPONSE" ]]; then
    break
  fi
  sleep 1
done

if [[ -z "${RESPONSE:-}" ]]; then
  die "service failed to become healthy — inspect: journalctl --user -u $SERVICE -e"
fi

PASSWORD="$(grep -E '^AUTH_PASSWORD=' "$ENV_FILE" | head -1 | cut -d= -f2)"

echo
echo "✓ Mission Control v$VERSION installed"
echo "  URL:       http://$(hostname -I | awk '{print $1}'):$PORT"
echo "  password:  $PASSWORD"
echo "  health:    $RESPONSE"
echo
echo "  status:    systemctl --user status $SERVICE"
echo "  logs:      journalctl --user -u $SERVICE -f"
echo "  upgrade:   bash $TMPL_DIR/upgrade.sh <new-tarball>"
