import { createServer } from 'http'
import {
  createHmac,
  createHash,
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  randomBytes,
  sign as cryptoSign,
  timingSafeEqual,
  type KeyObject,
} from 'crypto'
import type { UrlWithParsedQuery } from 'url'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import next from 'next'
import { loadEnvConfig } from '@next/env'
import { WebSocketServer, WebSocket } from 'ws'
import { initDb, db } from './src/lib/db'
import { morningReportConfig } from './src/lib/schema'
import { eq } from 'drizzle-orm'
import { startTunnel, stopTunnel } from './src/lib/morning-report/tunnel'
import { TerminalSessionManager } from './src/lib/terminal/session-manager'

// Auto-generate .env.local on first run
function bootstrapEnvLocal() {
  const envPath = join(process.cwd(), '.env.local')
  if (existsSync(envPath)) return

  console.log('[Bootstrap] First run detected, generating .env.local ...')

  const password = randomBytes(16).toString('base64url')
  const secret = randomBytes(32).toString('base64url')

  // Try to read gateway token from ~/.openclaw/openclaw.json
  let gatewayToken = ''
  try {
    const configPath = join(homedir(), '.openclaw', 'openclaw.json')
    const config = JSON.parse(readFileSync(configPath, 'utf8'))
    gatewayToken = config?.gateway?.auth?.token || ''
  } catch {}

  const lines = [
    '# Auto-generated by Mission Control on first run',
    '',
    '# OpenClaw Gateway',
    'OPENCLAW_GATEWAY_WS=ws://127.0.0.1:18789',
    'OPENCLAW_GATEWAY_HTTP=http://127.0.0.1:18789',
    `OPENCLAW_TOKEN=${gatewayToken}`,
    '',
    '# Authentication',
    `AUTH_PASSWORD=${password}`,
    `AUTH_SECRET=${secret}`,
    '',
    '# Server',
    'PORT=3737',
    'HOST=0.0.0.0',
    '',
  ]

  writeFileSync(envPath, lines.join('\n'))
  console.log('[Bootstrap] .env.local created')
  console.log(`[Bootstrap] Dashboard password: ${password}`)
  console.log('[Bootstrap] Save this password — it won\'t be shown again.')
  if (gatewayToken) {
    console.log('[Bootstrap] Gateway token auto-detected from ~/.openclaw/openclaw.json')
  } else {
    console.warn('[Bootstrap] No gateway token found. Set it in Settings page or .env.local')
  }
}

bootstrapEnvLocal()

// Load .env.local BEFORE reading any env vars
loadEnvConfig(process.cwd())

// Ensure ~/.local/bin is in PATH (common for user-installed tools like openclaw)
const localBin = join(homedir(), '.local', 'bin')
if (!process.env.PATH?.includes(localBin)) {
  process.env.PATH = `${localBin}:${process.env.PATH}`
}

const dev = process.env.NODE_ENV !== 'production'
const port = parseInt(process.env.PORT || '3737', 10)

// In production (standalone release), Next.js ships a pre-serialized config
// in `.next/required-server-files.json`. Inject it via the private env var
// Next.js's own standalone server uses, so `next()` skips re-reading the TS
// config file (which would pull in webpack, not shipped in standalone).
if (!dev && !process.env.__NEXT_PRIVATE_STANDALONE_CONFIG) {
  try {
    const rsfPath = join(process.cwd(), '.next', 'required-server-files.json')
    const raw = readFileSync(rsfPath, 'utf8')
    const parsed = JSON.parse(raw) as { config?: Record<string, unknown> }
    if (parsed.config) {
      process.env.__NEXT_PRIVATE_STANDALONE_CONFIG = JSON.stringify(parsed.config)
    }
  } catch {}
}

const app = next({ dev, dir: process.cwd() })
const handle = app.getRequestHandler()

// Auto-detect gateway token from ~/.openclaw/openclaw.json if not in env
function resolveGatewayToken(): string {
  const envToken = process.env.OPENCLAW_TOKEN
  if (envToken) return envToken

  try {
    const configPath = join(homedir(), '.openclaw', 'openclaw.json')
    const config = JSON.parse(readFileSync(configPath, 'utf8'))
    const token = config?.gateway?.auth?.token
    if (token) {
      console.log('[Gateway] Token auto-detected from ~/.openclaw/openclaw.json')
      return token
    }
  } catch {}

  console.warn('[Gateway] No token found in env or ~/.openclaw/openclaw.json')
  return ''
}

// OpenClaw gateway connection
const GATEWAY_WS = process.env.OPENCLAW_GATEWAY_WS || 'ws://127.0.0.1:18789'
// Note: the token is resolved per-reconnect inside connectGateway(), so a
// token rotation on the Gateway (e.g. after an OpenClaw upgrade) heals
// automatically once ~/.openclaw/openclaw.json is updated.
const AUTH_PASSWORD = process.env.AUTH_PASSWORD || ''
const AUTH_SECRET = process.env.AUTH_SECRET || ''

// -----------------------------------------------------------------------------
// OpenClaw device identity (Ed25519)
// Newer Gateways (2026.4+) clear requested scopes for token-only connections
// without a device identity, leaving every RPC with "missing scope: operator.read".
// Generate a persistent Ed25519 keypair and sign the connect.challenge payload;
// localhost connections are auto-paired by the Gateway so no manual approval is
// needed.
// -----------------------------------------------------------------------------

function base64UrlEncode(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

interface DeviceIdentity {
  privateKey: KeyObject
  publicKeyB64Url: string
  deviceId: string
}

function loadOrCreateDeviceIdentity(): DeviceIdentity {
  const dir = join(homedir(), '.mission-control')
  const keyPath = join(dir, 'gateway-device-key.pem')
  let privateKey: KeyObject
  try {
    if (existsSync(keyPath)) {
      privateKey = createPrivateKey({ key: readFileSync(keyPath, 'utf8'), format: 'pem' })
    } else {
      const { privateKey: pk } = generateKeyPairSync('ed25519')
      const pem = pk.export({ type: 'pkcs8', format: 'pem' }) as string
      try { writeFileSync(keyPath, pem, { mode: 0o600 }) } catch { /* best-effort persist */ }
      privateKey = pk
    }
  } catch (err) {
    console.warn('[Gateway] device key persist failed, using in-memory only:', (err as Error).message)
    privateKey = generateKeyPairSync('ed25519').privateKey
  }
  const publicKey = createPublicKey(privateKey)
  const jwk = publicKey.export({ format: 'jwk' }) as { x?: string }
  if (!jwk.x) throw new Error('Failed to extract Ed25519 public key')
  // JWK `x` already is base64url of the raw 32-byte key.
  const publicKeyB64Url = jwk.x
  const rawPub = Buffer.from(publicKeyB64Url.replace(/-/g, '+').replace(/_/g, '/')
    + '='.repeat((4 - publicKeyB64Url.length % 4) % 4), 'base64')
  const deviceId = createHash('sha256').update(rawPub).digest('hex')
  return { privateKey, publicKeyB64Url, deviceId }
}

const DEVICE_IDENTITY = loadOrCreateDeviceIdentity()
console.log(`[Gateway] Device identity ready (id=${DEVICE_IDENTITY.deviceId.slice(0, 12)}...)`)

let pairingAttempted = false

/** Find our pending pairing request via `openclaw devices list --json`
 *  and approve it. Returns true if approved, false otherwise.
 *
 *  Gateway writes the pending request asynchronously after sending the
 *  1008 close, so the first query right after disconnect can race ahead
 *  of the persist. Retry a few times with a short backoff. */
async function tryAutoApproveDevice(): Promise<boolean> {
  const { execFile } = await import('child_process')
  const { promisify } = await import('util')
  const execFileAsync = promisify(execFile)

  const findRequestId = async (): Promise<string | null> => {
    const { stdout } = await execFileAsync('openclaw', ['devices', 'list', '--json'], {
      timeout: 10000,
      env: process.env,
    })
    const data = JSON.parse(stdout)
    const pending: Array<{ requestId?: string; deviceId?: string }> = Array.isArray(data?.pending) ? data.pending : []
    const req = pending.find((r) => r.deviceId === DEVICE_IDENTITY.deviceId)
    return req?.requestId ?? null
  }

  try {
    let requestId: string | null = null
    for (let attempt = 0; attempt < 5; attempt++) {
      requestId = await findRequestId()
      if (requestId) break
      await new Promise((r) => setTimeout(r, 500))
    }
    if (!requestId) {
      console.warn('[Gateway] No pending pairing request matching our device id after 5 attempts')
      return false
    }
    console.log(`[Gateway] Approving pairing request ${requestId}...`)
    await execFileAsync('openclaw', ['devices', 'approve', requestId], {
      timeout: 10000,
      env: process.env,
    })
    return true
  } catch (err) {
    console.error('[Gateway] Auto-approve failed:', (err as Error).message)
    return false
  }
}

// Terminal session manager
let terminalManager: TerminalSessionManager | null = null
try {
  terminalManager = new TerminalSessionManager()
  console.log('[Terminal] Session manager initialized')
} catch (e) {
  console.warn('[Terminal] node-pty not available, terminal feature disabled:', (e as Error).message)
}

// Wiki watcher — polls capture vault for new raw/transcripts files and
// pushes them into the memory-wiki sources/ layer. No-op if openclaw isn't
// configured yet (ingest call will fail silently and we'll retry next tick).
;(async () => {
  try {
    const { startWikiWatcher } = await import('./src/lib/second-brain/wiki/watcher')
    startWikiWatcher()
  } catch (err) {
    console.warn('[Wiki] watcher init skipped:', (err as Error).message)
  }
})()

// Broadcast to all connected clients
function broadcast(wss: WebSocketServer, message: string) {
  wss.clients.forEach(client => {
    if (client.readyState === WebSocket.OPEN) {
      client.send(message)
    }
  })
}

// Connect to OpenClaw gateway and relay events
let gatewayWs: WebSocket | null = null
let reconnectTimer: ReturnType<typeof setTimeout> | null = null

// RPC pending requests for gateway JSON-RPC calls
const pendingRequests = new Map<string, { resolve: (value: unknown) => void; reject: (reason: unknown) => void; timer: ReturnType<typeof setTimeout> }>()

;(globalThis as any).__gatewayRpc = (method: string, params?: unknown): Promise<unknown> => {
  return new Promise((resolve, reject) => {
    if (!gatewayWs || gatewayWs.readyState !== WebSocket.OPEN) {
      return reject(new Error('Gateway WebSocket not connected'))
    }
    const id = Math.random().toString(36).substring(2) + Date.now().toString(36)
    const timer = setTimeout(() => {
      pendingRequests.delete(id)
      reject(new Error(`RPC timeout for ${method}`))
    }, 10_000)
    pendingRequests.set(id, { resolve, reject, timer })
    gatewayWs.send(JSON.stringify({ type: 'req', id, method, params: params ?? {} }))
  })
}

function connectGateway(wss: WebSocketServer) {
  try {
    // Re-read token every reconnect so token rotation (OpenClaw upgrades
    // regenerate it) is picked up without a dashboard restart.
    const token = resolveGatewayToken()

    const ws = new WebSocket(GATEWAY_WS, {
      headers: { Origin: 'http://127.0.0.1:18789' },
    })
    gatewayWs = ws

    ws.on('open', () => {
      console.log('[Gateway] Connected to OpenClaw, waiting for challenge...')
    })

    ws.on('message', (data) => {
      const raw = data.toString()
      try {
        const msg = JSON.parse(raw)

        // Handle challenge-response auth
        if (msg.type === 'event' && msg.event === 'connect.challenge') {
          const reqId = Math.random().toString(36).substring(2)
          const clientId = 'cli'
          const clientMode = 'backend'
          const role = 'operator'
          const scopes = [
            'operator.admin',
            'operator.read',
            'operator.write',
            'operator.approvals',
            'operator.pairing',
            'operator.talk.secrets',
          ]
          const signedAtMs = Date.now()
          const nonce = typeof msg?.payload?.nonce === 'string' ? msg.payload.nonce : ''

          // Build v2 device-auth payload matching Gateway's buildDeviceAuthPayload().
          const payload = [
            'v2',
            DEVICE_IDENTITY.deviceId,
            clientId,
            clientMode,
            role,
            scopes.join(','),
            String(signedAtMs),
            token,
            nonce,
          ].join('|')
          const signatureB64Url = base64UrlEncode(
            cryptoSign(null, Buffer.from(payload, 'utf8'), DEVICE_IDENTITY.privateKey),
          )

          ws.send(JSON.stringify({
            type: 'req',
            id: reqId,
            method: 'connect',
            params: {
              minProtocol: 3,
              maxProtocol: 3,
              client: {
                id: clientId,
                version: '1.0.0',
                platform: 'node',
                mode: clientMode,
                instanceId: 'mission-control-server',
              },
              role,
              scopes,
              caps: [],
              auth: { token: token },
              device: {
                id: DEVICE_IDENTITY.deviceId,
                publicKey: DEVICE_IDENTITY.publicKeyB64Url,
                signature: signatureB64Url,
                nonce,
                signedAt: signedAtMs,
              },
              userAgent: 'mission-control/1.0',
              locale: 'zh-TW',
            },
          }))
          return
        }

        // Handle RPC responses
        if (msg.type === 'res' && msg.id && pendingRequests.has(msg.id)) {
          const pending = pendingRequests.get(msg.id)!
          pendingRequests.delete(msg.id)
          clearTimeout(pending.timer)
          if (msg.ok) {
            pending.resolve(msg.payload)
          } else {
            pending.reject(new Error(msg.error?.message || 'RPC error'))
          }
          return
        }

        // Log auth result
        if (msg.type === 'res' && msg.ok && msg.payload?.type === 'hello-ok') {
          console.log('[Gateway] Authenticated successfully ✓')
        }
      } catch {}

      // Relay all messages to browser clients
      broadcast(wss, raw)
    })

    ws.on('close', (code, reason) => {
      const reasonStr = reason?.toString() || ''
      gatewayWs = null
      // Reject all pending RPC requests
      for (const [, pending] of pendingRequests) {
        clearTimeout(pending.timer)
        pending.reject(new Error('Gateway disconnected'))
      }
      pendingRequests.clear()

      // First-run pairing: auto-approve our own device via `openclaw devices`
      // when localhost Gateway rejects with "pairing required". Retry once.
      if (code === 1008 && reasonStr.includes('pairing required') && !pairingAttempted) {
        pairingAttempted = true
        console.log('[Gateway] Pairing required — attempting auto-approval for our device...')
        tryAutoApproveDevice().then((approved) => {
          if (approved) {
            console.log('[Gateway] Device approved, reconnecting in 1s...')
            reconnectTimer = setTimeout(() => connectGateway(wss), 1000)
          } else {
            console.error('[Gateway] Auto-approval failed. Run: openclaw devices approve --latest')
          }
        })
        return
      }

      // Auth failure — keep retrying on a slow cadence so token rotations
      // (e.g. OpenClaw upgrades that regenerate ~/.openclaw/openclaw.json)
      // heal on their own. The re-read at the top of connectGateway() picks
      // up the new token. 30s backoff keeps a genuinely bad config from
      // hammering the gateway.
      const isAuthFailure = code === 1008 || reasonStr.includes('identity required') || reasonStr.includes('unauthorized')
      if (isAuthFailure) {
        console.error(`[Gateway] Auth failed (${code} ${reasonStr}). Retrying in 30s with a fresh token...`)
        console.error('[Gateway] If this persists, check the token in ~/.openclaw/openclaw.json or .env.local')
        reconnectTimer = setTimeout(() => connectGateway(wss), 30000)
        return
      }

      console.log(`[Gateway] Disconnected (${code} ${reasonStr}), reconnecting in 5s...`)
      reconnectTimer = setTimeout(() => connectGateway(wss), 5000)
    })

    ws.on('error', (err) => {
      console.error('[Gateway] Error:', err.message)
    })
  } catch (err) {
    console.error('[Gateway] Connection failed:', err)
    reconnectTimer = setTimeout(() => connectGateway(wss), 5000)
  }
}

function verifyWsSession(req: import('http').IncomingMessage): boolean {
  if (!AUTH_PASSWORD) return true
  const cookieHeader = req.headers.cookie || ''
  const match = cookieHeader.match(/mc_session=([^;]+)/)
  if (!match) return false
  const token = match[1]
  const lastDot = token.lastIndexOf('.')
  if (lastDot === -1) return false
  const payload = token.substring(0, lastDot)
  const sig = token.substring(lastDot + 1)
  const expected = createHmac('sha256', AUTH_SECRET).update(payload).digest('hex')
  try {
    const sigBuf = Buffer.from(sig, 'hex')
    const expectedBuf = Buffer.from(expected, 'hex')
    if (sigBuf.length !== expectedBuf.length) return false
    return timingSafeEqual(sigBuf, expectedBuf)
  } catch {
    return false
  }
}

app.prepare().then(() => {
  // Initialize DB
  initDb()
  console.log('[DB] SQLite initialized')

  // Auto-start tunnel if morning report is enabled
  {
    const getConf = (key: string) =>
      db.select().from(morningReportConfig).where(eq(morningReportConfig.key, key)).get()?.value ?? ''
    const enabled = getConf('enabled') === 'true'
    const publicDir = getConf('publicDir')
    if (enabled && publicDir && existsSync(publicDir)) {
      startTunnel(publicDir)
        .then(({ url }) => console.log(`[Tunnel] Auto-started: ${url}`))
        .catch((err) => console.warn('[Tunnel] Auto-start failed:', (err as Error).message))
    }
  }

  const server = createServer((req, res) => {
    const url = new URL(req.url!, `http://${req.headers.host || 'localhost'}`)
    const parsedUrl: UrlWithParsedQuery = {
      pathname: url.pathname,
      query: Object.fromEntries(url.searchParams),
    } as UrlWithParsedQuery

    // Serve vnc-viewer.html with SAMEORIGIN to allow iframe embedding
    if (url.pathname === '/vnc-viewer.html') {
      const filePath = join(process.cwd(), 'public', 'vnc-viewer.html')
      if (existsSync(filePath)) {
        const content = readFileSync(filePath)
        res.writeHead(200, {
          'Content-Type': 'text/html; charset=utf-8',
          'X-Frame-Options': 'SAMEORIGIN',
          'X-Content-Type-Options': 'nosniff',
        })
        res.end(content)
        return
      }
    }

    handle(req, res, parsedUrl)
  })

  // WebSocket server for browser clients — noServer mode so we don't
  // intercept Next.js HMR upgrade requests (/_next/webpack-hmr).
  const wss = new WebSocketServer({ noServer: true })

  const terminalWss = new WebSocketServer({ noServer: true })

  wss.on('connection', (ws, req) => {
    console.log('[WS] Client connected from', req.socket.remoteAddress)

    ws.on('message', (data) => {
      // Forward client messages to gateway
      if (gatewayWs?.readyState === WebSocket.OPEN) {
        gatewayWs.send(data.toString())
      }
    })

    ws.on('close', () => {
      console.log('[WS] Client disconnected')
    })
  })

  // Only handle upgrade for our /ws paths; let Next.js handle HMR upgrades
  server.on('upgrade', (req, socket, head) => {
    const upgradeUrl = new URL(req.url!, `http://${req.headers.host || 'localhost'}`)
    const pathname = upgradeUrl.pathname
    const query = Object.fromEntries(upgradeUrl.searchParams) as Record<string, string>
    if (pathname === '/ws') {
      if (!verifyWsSession(req)) {
        socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n')
        socket.destroy()
        return
      }
      wss.handleUpgrade(req, socket, head, (ws) => {
        wss.emit('connection', ws, req)
      })
    } else if (pathname === '/ws/terminal') {
      if (!verifyWsSession(req)) {
        socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n')
        socket.destroy()
        return
      }
      if (!terminalManager) {
        socket.write('HTTP/1.1 503 Service Unavailable\r\n\r\n')
        socket.destroy()
        return
      }
      const sessionId = query.sessionId as string
      terminalWss.handleUpgrade(req, socket, head, (ws) => {
        if (!sessionId || !terminalManager!.attachWebSocket(sessionId, ws)) {
          ws.close(1008, 'invalid session')
        }
      })
    } else if (pathname === '/ws/vnc-proxy') {
      // TCP-level proxy to local websockify for VNC access
      // This avoids exposing the websockify port externally
      const vncPort = parseInt(query.port as string)
      if (!vncPort || isNaN(vncPort)) {
        socket.write('HTTP/1.1 400 Bad Request\r\n\r\n')
        socket.destroy()
        return
      }
      const net = require('net') as typeof import('net')
      const upstream = net.createConnection({ host: '127.0.0.1', port: vncPort }, () => {
        // Forward the original HTTP upgrade request to websockify
        const rawReq = `${req.method} / HTTP/1.1\r\n` +
          Object.entries(req.headers)
            .filter(([k]) => k !== 'host')
            .map(([k, v]) => `${k}: ${v}`)
            .join('\r\n') +
          `\r\nHost: 127.0.0.1:${vncPort}\r\n\r\n`
        upstream.write(rawReq)
        // Pipe bidirectionally after sending the request
        upstream.pipe(socket)
        socket.pipe(upstream)
      })
      upstream.on('error', () => {
        socket.write('HTTP/1.1 502 Bad Gateway\r\n\r\n')
        socket.destroy()
      })
      socket.on('close', () => upstream.destroy())
      socket.on('error', () => upstream.destroy())
    }
    // Other paths (/_next/webpack-hmr) are handled by Next.js internally
  })

  // Connect to OpenClaw gateway
  connectGateway(wss)

  // Export terminal manager for API routes
  ;(globalThis as Record<string, unknown>).__terminalManager = terminalManager

  function gracefulShutdown() {
    console.log('[Server] Shutting down...')
    stopTunnel()
    terminalManager?.shutdown()
    server.close(() => process.exit(0))
    // Force exit after 5 seconds if close hangs
    setTimeout(() => process.exit(1), 5000).unref()
  }
  process.on('SIGTERM', gracefulShutdown)
  process.on('SIGINT', gracefulShutdown)

  const host = process.env.HOST || '127.0.0.1'
  server.listen(port, host, () => {
    console.log(`\n🚀 Mission Control running`)
    console.log(`   Local:   http://localhost:${port}`)
    console.log(`   Bind:    http://${host}:${port}`)
    console.log(`   Gateway: ${GATEWAY_WS}\n`)
  })
})
