import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import os from 'os'

/** Auto-loading the OpenCLI browser extension.
 *
 * Chromium takes `--load-extension` at launch. Google Chrome — which is what
 * the browser installer actually installs — ignores it, so on every real
 * install the extension sat unpacked in ~/.opencli/extension and the operator
 * had to load it by hand from chrome://extensions.
 *
 * Chrome does still accept the extension over CDP (`Extensions.loadUnpacked`),
 * and the browser already runs with --remote-debugging-port, so no extra flag
 * is needed. What it does NOT do is remember: the load is dropped on restart
 * (verified against Chrome 152 — gone from /json/list, from Preferences and
 * from Secure Preferences). So this runs as the unit's ExecStartPost, once per
 * Chrome start, rather than as a one-off install step. */

/** Whether this Chrome needs the CDP path. Chromium gets the extension from
 * --load-extension at launch; loading it again here would register a second
 * copy of the same extension. */
export function shouldLoadExtensionViaCdp(
  chromeBin: string,
  extensionInstalled: boolean,
): boolean {
  if (!extensionInstalled) return false
  return !chromeBin.toLowerCase().includes('chromium')
}

/** The ExecStartPost loader.
 *
 * Uses the global WebSocket built into Node 22+ (every ABI the release tarball
 * ships for), so it needs nothing on disk but node itself. Always exits 0:
 * ExecStartPost failure would mark the browser unit failed, and a browser that
 * started correctly must not be reported as broken because an extension did
 * not load. */
export function buildOpencliLoaderScript(cdpPort: number, extensionDir: string): string {
  return `// Generated by Mission Control — loads the OpenCLI extension into the
// running Chrome. Re-run on every Chrome start: the load does not survive a
// restart. Safe to delete; the browser works without it.
const CDP = 'http://127.0.0.1:${cdpPort}'
const EXT = ${JSON.stringify(extensionDir)}

const log = (m) => console.log('[opencli-extension] ' + m)

async function version() {
  try {
    const r = await fetch(CDP + '/json/version', { signal: AbortSignal.timeout(2000) })
    return r.ok ? await r.json() : null
  } catch { return null }
}

async function main() {
  // Chrome's CDP endpoint is not up the moment ExecStart returns.
  let v = null
  for (let i = 0; i < 60; i++) {
    v = await version()
    if (v && v.webSocketDebuggerUrl) break
    await new Promise((r) => setTimeout(r, 1000))
  }
  if (!v || !v.webSocketDebuggerUrl) return log('CDP never became ready — skipped')

  const ws = new WebSocket(v.webSocketDebuggerUrl)
  await new Promise((res, rej) => {
    ws.onopen = res
    ws.onerror = rej
    setTimeout(() => rej(new Error('ws open timeout')), 10000)
  })

  const reply = await new Promise((res, rej) => {
    const onMsg = (e) => {
      const m = JSON.parse(e.data)
      if (m.id === 1) { ws.removeEventListener('message', onMsg); res(m) }
    }
    ws.addEventListener('message', onMsg)
    ws.send(JSON.stringify({ id: 1, method: 'Extensions.loadUnpacked', params: { path: EXT } }))
    setTimeout(() => rej(new Error('loadUnpacked timeout')), 20000)
  })
  ws.close()

  if (reply.error) log('load failed: ' + JSON.stringify(reply.error))
  else log('loaded ' + (reply.result && reply.result.id))
}

main().catch((e) => log('skipped: ' + (e && e.message))).finally(() => process.exit(0))
`
}

export function getOpencliLoaderPath(): string {
  return join(os.homedir(), '.config', 'mission-control', 'load-opencli-extension.mjs')
}

/** Write the loader next to the other generated browser config, NOT inside the
 * MCC install dir — ExecStartPost has to keep working across MCC upgrades,
 * which swap the versioned install directory underneath it. */
export function writeOpencliLoader(cdpPort: number, extensionDir: string): string {
  const target = getOpencliLoaderPath()
  if (!existsSync(dirname(target))) mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, buildOpencliLoaderScript(cdpPort, extensionDir), 'utf8')
  return target
}
